<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="<?php echo asset('/css/app.css'); ?>">

	<title>Žinutės</title>
</head>
<body>
	<div id="wrapper">
		<h1>Jūsų žinutės</h1>
		<form id="div-comment-container" method="POST">
			<p>
				<label for="fullname">Vardas, pavardė *</label><br/>
				<input type="text" name="fullname" />
			</p>
			<p>
				<label for="birthdate">Gimimo data *</label><br/>
				<!-- Galima butu panaudoti type="date", bet po to reiktu formatuoti daug...  -->
				<input type="text" name="birthdate" placeholder="1992-02-04" />
			</p>
			<p>
				<label for="email">El.pašto adresas</label><br/>
				<input type="email" name="email" />
			</p>
			<p>
				<label for="message">Jūsų žinutė *</label><br/>
				<textarea name="message"></textarea>
			</p>
			<p>
				<span>* - privalomi laukai</span>
				
				<input type="submit" value="Skelbti" id="button-submit-comment">
				
				<img src="img/ajax-loader.gif" style="display: none;">
			</p>
		</form>
		<ul id="ul-comments-list">
			<?php if (count($messages) == 0): ?>
			<li>
				<strong>Šiuo metu žinučių nėra. Būk pirmas!</strong>
			</li>
			<?php else: ?>
			<?php foreach($messages as $message): ?>
			<li>
				<span><?php echo date('Y-m-d H:i', strtotime($message->created_at)); ?></span> <?php echo $message->email ? sprintf('<a href="mailto:%s">%s</a>', $message->email, $message->fullname) : $message->fullname ?>, <?php date('Y') - date('Y', strtotime($message->birthdate)) ?> m.<br/>
				<?php echo $message->message ?>
			</li>
			<?php endforeach; ?>
			<?php endif; ?>
		</ul>
		<p id="pages">
			<?php if ($page > 1): ?>
			<a href="?page=<?php echo $page - 1 ?>" title="atgal">atgal</a>
			<?php endif;?>
			<?php echo $page; ?>
			<?php if ($page < $pages): ?>
			<a href="?page=<?php echo $page + 1 ?>" title="toliau">toliau</a>
			<?php endif;?>
		</p>
	</div>
	<script>
		var _PER_PAGE = <?php echo $per_page; ?>;
	</script>
	<script src="<?php echo asset('/js/app.js'); ?>"></script>
</body>
</html>